### ISSUE TITLE
ValueError: Target size (torch.Size([128, 1])) must be the same as input size (torch.Size([256, 1]))

### ISSUE THREAD

**Issue by fly2tortoise** [shiming-chen/CDE-GAN#3]
Hello, distinguished researcher
Your research is very interesting and contributes greatly to evolutionary algorithms. But I have some problems when I reproduce your code, can you help me?
Personally, I guess I forgot to modify a parameter. It is ok for me to reproduce EGAN before.

![image](https://user-images.githubusercontent.com/85298331/167897760-0e656464-8922-4878-be73-9a3171a39477.png)
Looking forward to your reply and best wishes

**Comment by shiming-chen** [comment]
@fly2tortoise 

Thank you for interesting in our work.
Just as you guesting, you may not correctly modify the related hyperparameter.
Please carefully check your codes.

Best!
Shiming

**Comment by fly2tortoise** [comment]
![image](https://user-images.githubusercontent.com/85298331/177029523-061bc1c0-240c-4158-9d08-4aa69cec1e7c.png)
Distinguished researcher, your code may still have some problems, and I'm still not working properly.  but

**Comment by qq272574497** [comment]
I have the same problem, have you solved it?

**Comment by fly2tortoise** [comment]
> I have the same problem, have you solved it?
It's a better solution, I forget the specifics, it seems to require deleting part of the Tensor list, I'll dig through the code sometime.

**Comment by qq272574497** [comment]
> It's a better solution, I forget the specifics, it seems to require deleting part of the Tensor list, I'll dig through the code sometime.

wait your answer

**Comment by fly2tortoise** [comment]
> > It's a better solution, I forget the specifics, it seems to require deleting part of the Tensor list, I'll dig through the code sometime.
> 
> wait your answer

![image](https://github.com/shiming-chen/CDE-GAN/assets/85298331/18bea17c-2e5a-4717-aa1b-8526f5723d38)
I changed one line of code and it works fine, it's in models/cdegan_model.py,about 150 lines or so

**Comment by qq272574497** [comment]
> > > It's a better solution, I forget the specifics, it seems to require deleting part of the Tensor list, I'll dig through the code sometime.
> > 
> > 
> > wait your answer
> 
> ![image](https://user-images.githubusercontent.com/85298331/258584465-18bea17c-2e5a-4717-aa1b-8526f5723d38.png) I changed one line of code and it works fine, it's in models/cdegan_model.py,about 150 lines or so

in options/train_options.py,add bs ,it work!
parser.add_argument('--bs', type=int, default=2048, help='dataset fragment')

**Comment by qq272574497** [comment]
> @fly2tortoise
> 
> Thank you for interesting in our work. Just as you guesting, you may not correctly modify the related hyperparameter. Please carefully check your codes.
> 
> Best! Shiming

I would like to ask you one more question. Could you repeat the experiment? Don't know where the code is

![image](https://github.com/shiming-chen/CDE-GAN/assets/66626324/344d6001-2af0-47ef-9ccc-743e66407fdd)

**Comment by qq272574497** [comment]
> @fly2tortoise
> 
> Thank you for interesting in our work. Just as you guesting, you may not correctly modify the related hyperparameter. Please carefully check your codes.
> 
> Best! Shiming

I would like to ask you one more question. Can you calculate the fid of TTUR?

**Comment by fly2tortoise** [comment]
> Yes, CDE-GAN is a very good paper. Please configure your environment strictly according to the settings given by the author. Use tensorflow 1.15 for computation.

**Comment by fly2tortoise** [comment]
qq272574497 , please install and configure according to the following environment, if you can't run TTUR, the probability is that it's a problem with the TensorFlow version as well as CUDA, thanks.
PyTorch 1.3.0
TensorFlow 1.15.0
cuda 10.0

**Comment by qq272574497** [comment]
> qq272574497 , please install and configure according to the following environment, if you can't run TTUR, the probability is that it's a problem with the TensorFlow version as well as CUDA, thanks. PyTorch 1.3.0 TensorFlow 1.15.0 cuda 10.0

cuda 11.7 TensorFlow 2.X  PyTorch 1.7 it work

**Comment by qq272574497** [comment]
> @fly2tortoise
> 
> Thank you for interesting in our work. Just as you guesting, you may not correctly modify the related hyperparameter. Please carefully check your codes.
> 
> Best! Shiming


![258719342-344d6001-2af0-47ef-9ccc-743e66407fdd](https://github.com/shiming-chen/CDE-GAN/assets/66626324/6d1a10ec-a074-428e-91af-d4eef623238c)


I would like to ask you one more question. Could you repeat the experiment? Don't know where the code is
